name: livekit_example
description: Example app that uses LiveKit Flutter SDK
publish_to: 'none'

version: 1.0.0

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.18.1
  flutter_background: ^1.1.0
  permission_handler: ^10.2.0
  provider: ^6.0.1
  logging: ^1.0.1
  google_fonts: ^4.0.4
  flutter_svg: ^2.0.5
  sendbird_chat_sdk: ^4.1.0
  sendbird_chat_widget: ^1.0.1
  get: ^4.6.5
  fluttertoast: ^8.2.2
  scrollable_positioned_list: ^0.3.5
  file_picker: ^5.2.7 # FileMessage
  #+ Push Notifications
  shared_preferences: ^2.1.0
  flutter_local_notifications: ^14.0.1
  push: ^1.0.5
  flutter_app_badger: ^1.5.0
  livekit_client:
    path: ../

    # git:
    #   url: https://github.com/livekit/client-sdk-flutter
    #   ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - images/logo-dark.svg
